filegroup(
    name = "httplib",
    srcs = glob(["httplib/httplib.h"]),
    visibility = ["//visibility:public"]
)

filegroup(
    name = "main",
    srcs = glob(["main.cc"]),
    visibility = ["//visibility:public"],
)